Create Database customershoppingbehavior
Use customershoppingbehavior

Select * from [dbo].[customer]

-- What is the total revenue generated by male and female customer?
Select Gender, SUM(Purchase_Amount) as Revenue
from [dbo].[customer]
group by gender

--Which customer used a discount but still spent more than the average purchase amount?
Select customer_id, purchase_amount
from [dbo].[customer]
where Discount_Applied = 'Yes' and Purchase_Amount >= (select AVG(Purchase_Amount) from [dbo].[customer])


--which are the top 5  products with highest average review rating?
select Top(5) Item_Purchased, Round(AVG(Review_rating),2) as Avg_Rating from [dbo].[customer]
group by Item_Purchased
order by Avg_Rating desc

-- Compare the average purchase amount between standard and Express shipping?
Select Shipping_Type,
Avg(Purchase_Amount) as Average_Purchase_Amount from [dbo].[customer]
where Shipping_Type in ('Standard', 'Express')
group by Shipping_Type

--Do subscribed customer spend more? Compare average spend and total revenue between subscriber and non- subscriber?
Select Subscription_Status,
Count(Customer_ID) as total_customer, 
AVG(purchase_amount) as avg_spend,
SUM(purchase_amount) as total_revenue from [dbo].[customer]
group by subscription_status
Order by total_revenue, avg_spend

--Which 5 products have the highest percentage of purchases with discount applied?
Select Top 5 item_purchased,
100 * Sum(Case when discount_applied = 'Yes' then 1 END)/Count(*) as discount_percentage
from [dbo].[customer]
Group by Item_Purchased
Order by Discount_Percentage desc;

-- Segment customer into New, Returning and loyal based 
--on their total number of previous purchases and show the count of each segment?
With Customer_Type as (
Select Customer_ID, previous_purchases,
case when previous_purchases = 1 then 'New'
When previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
End as Customer_Segment
from [dbo].[customer]
)
Select Customer_Segment, count(*) as 'Number of Customer'
from Customer_type
group by Customer_Segment

-- What are the top 3 most purchased product within each category?
With Item_Counts as (
Select category, item_purchased,
Count(Customer_id) as total_orders,
Row_Number()over(partition by Category order by count(Customer_id) Desc) as item_rank
from [dbo].[customer]
group by category, item_purchased
)
Select item_rank, category, item_purchased,total_orders 
from item_counts
where item_rank <= 3;

-- Are customer who are repeat buyer (more than 5 purchases) also likely to subscribe?
Select subscription_status,
Count(Customer_id) as repeat_buyers
from [dbo].[customer]
where previous_purchases >5
group by subscription_status

-- What is the revenue contribution of each age group?
Select age_group,
SUM(purchase_amount) as total_revenue
from [dbo].[customer]
group by age_group
order by total_revenue desc

